name: Auto Sign-in

on:
  schedule:
    - cron: "5 5 * * *"  # 对应 UTC 05:05，即北京时间 13:05
  workflow_dispatch: # 允许手动触发

jobs:
  sign_in:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. 运行签到脚本
      - name: Run sign-in script
        env:
          NAVIX_EMAIL: ${{ secrets.NAVIX_EMAIL }}
          NAVIX_PASSWORD: ${{ secrets.NAVIX_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python sign_in.py
