name: Auto Navix Sign-in

# 每天定时执行，可以修改 cron 表达式
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点执行（北京时间 8 点）
  workflow_dispatch:  # 手动触发

jobs:
  sign_in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Navix Sign-in
        env:
          NAVIX_EMAIL: ${{ secrets.NAVIX_EMAIL }}
          NAVIX_PASSWORD: ${{ secrets.NAVIX_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python sign_in.py
