name: Test Auto Sign-in

on:
  schedule:
    - cron: "*/1 * * * *"  # 每分钟执行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: read  # 只需要读取仓库内容，安全

jobs:
  test_run:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. 运行签到脚本并输出北京时间
      - name: Run test sign-in script
        env:
          NAVIX_EMAIL: ${{ secrets.NAVIX_EMAIL }}
          NAVIX_PASSWORD: ${{ secrets.NAVIX_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          echo "当前北京时间：$(date -d '+8 hour')"  # 输出北京时间
          python sign_in.py
