name: Cron Debug

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Beijing Time
        run: echo "北京时间：$(date -d '+8 hour')"
